package main

func main() {
	//helloWorld()
	//initVarTest()
	//testArraySliceDict()
	//conditionTest()
	//loopTest()
	//coroutineTest()
	//channelTest()
	//interfaceTest()
	//mysqlTest()
	//goServer()
	//ginServer()
	//panicTest()
	//errorTest()
	//recoverTest()
	//ChannelSyncLockPractice()
	//waitGroupTest()
	//InitConfig()
	//MutexTest()
	//RWMutexTest()
	//DeadlockScenario1()
	//DeadlockScenario2()
	//MySyncMapTest()
	//SyncMapTest()
	//AtomicTest()
	//SelectTest()
	//ContextTest()
	//TimerTest()
	//TickerTest()
	GoroutinePoolTest()
}
